name: vps-frontend

services:
  frontend:
    build:
      context: .
      target: runner
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.bunkhosting.nl
      - NEXT_PUBLIC_WEBSITE_URL=https://bunkhosting.nl
